sudo : required

services:
    - docker

before_install:
    - docker build -t chrisjerry9618/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true chrisjerry9618/react-test npm run test


after_success:
    - docker build -t chrisjerry9618/multi-client ./client
    - docker build -t chrisjerry9618/multi-server ./server
    - docker build -t chrisjerry9618/multi-worker ./worker
    - docker build -t chrisjerry9618/multi-nginx ./nginx

    ###login to cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    ##Push Images to Docker Hub
    - docker push chrisjerry9618/multi-client
    - docker push chrisjerry9618/multi-server
    - docker push chrisjerry9618/multi-worker
    - docker push chrisjerry9618/multi-nginx

deploy:
    provider: elasticbeanstalk
    region : 'us-east-1'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-us-east-1-846467755765'
    bucket_path: 'MultiDocker'
    on:
        branch : master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
 
language: generic
